version: '3.8'

services:
  ai-service:
    build: ./ai-service
    ports:
      - "5001:5001"
    env_file:
      - .env       # Reuse root .env file
    environment:
      - FLASK_ENV=production

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env       # Share the same .env with server
    environment:
      - NODE_ENV=production

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
